name: Generate documentation versions report
on:
  schedule:
    - cron: '17 4 1 * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-24.04
    if: github.repository == 'freeCodeCamp/devdocs'
    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@84684c07c1965536eb4802c8daf1a77968df0cb1 # v1.239.0
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Generate report
      run: bundle exec thor updates:check --github-token ${{ secrets.DEVDOCS_BOT_PAT }} --upload
